repos:
  - repo: local
    hooks:
      - id: format
        name: format with oxfmt
        entry: npm run format
        language: system
        pass_filenames: false
        files: \.(ts|tsx)$

      - id: lint
        name: lint with oxlint
        entry: npm run lint
        language: system
        pass_filenames: false
        files: \.(ts|tsx)$

      - id: validate
        name: validate config
        entry: npm run validate
        language: system
        pass_filenames: false
        files: \.(json|mjs|js)$

      - id: typecheck
        name: typecheck typescript
        entry: npm run typecheck
        language: system
        pass_filenames: false
        files: \.(ts|tsx)$

      - id: test
        name: run unit tests
        entry: npm run test
        language: system
        pass_filenames: false
        files: \.(ts|tsx|js|mjs)$
